version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mainnet
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mysql
    volumes:
      - mysql:/var/lib/mysql
      - "./init/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - mainnet
networks:
  mainnet:
volumes:
  mysql: